message:
  enable: '§b已启用.'
  disable: '§7已卸载.'
  helpMsg:
    - '§e===========§bILoreEdit§e==========='
    - '§a/lore name <名字> §7---- §b设置物品名字'
    - '§a/lore add <内容> §7---- §b添加一行Lore'
    - '§a/lore set <行号> <内容> §7---- §b修改指定行的Lore'
    - '§a/lore ins <行号> <内容> §7---- §b在指定行插入Lore'
    - '§a/lore del [行号] §7---- §b删除指定行的Lore,不指定行号则删除末行'
    - '§a/lore clear name §7---- §b清除物品名字'
    - '§a/lore clear lore §7---- §b清除所有Lore'
    - '§e/ILoreEdit help §7---- §a查看指令帮助'
    - '§e/ILoreEdit reload §7---- §a重载插件配置'
    - '§e/ILoreEdit version §7---- §a查看插件版本'
  canOnlyPlayer: '§b本命令只能玩家使用!'
  argsError: '§c错误的命令参数!'
  reloaded: '§a配置文件重载完成.'
  noItem: '§d你确定你手里有物品???'
  editDisplayName: '§a已修改物品显示名.'
  addLore: '§a已添加Lore.'
  noLore: '§b该物品没有Lore,你要修改什么?'
  invalidLine: '§4你输入的行号不是一个有效的数字.'
  errorLine: '§b你数数一共有几行···'
  zeroLine: '§b行数从1开始.'
  setLore: '§a已修改Lore.'
  noLore-ins: '§b该物品没有Lore,你想怎么插入?'
  insLore: '§a已插入Lore.'
  noLore-del: '§b该物品没有Lore,你要删除啥?'
  delLore: '§a已删除Lore.'
  clearDisplayName: '§a已清除物品显示名.'
  clearLore: '§a已清除Lore.'
  saveError: '§c保存修改失败,请重试.'